---
title: "Final Assignment Models Predictors"
author: "Eduard Romero / Carlos Bejarano / Juan Cepeda"
date: "2023-05-27"
output: pdf_document
header-includes:
  - \usepackage{xcolor}
  - \usepackage{titling}
  - \pretitle{\begin{center}\Large\color{blue}\textbf}
  - \posttitle{\end{center}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Problem definition

Mobile robotics is a popular solution for exploration of hostile environments (such as toxic or radioactive
environments) where a direct human intervention is not possible. In this project it is asked that each team
implements a robotic explorer and simulates 3 different environments.

-   1.1 A total of 3 different environments needs to be simulated. Each environment needs to provide at least 3
conditions that can be sensed by the robot.
-   1.1.2 The robot needs to be able of moving from one environment to another.
-   1.1.3 Configuration of the environments (order) must be interchangeable.
-   1.1.4 The robot needs to acquire 3 or more sensor signals that can be use as predictors for supervised algorithms

# 1.1 Controlled environments
  
  - Hot Room.
  - Cold Room.
  - Toxic Room.

# 1.1.2 Robot characteristics
  
  The main features of our robot are as follows:
  
  - MCU Arduino.
  - Micromotors DC.
  - PCB.
  - Battery LIPO 7.4V 300mAh.
  - Driver motor TB6612FNG.
  - Bluetooth HC06.
  
# 1.1.3 Configuration enviroments

The configuration of our 3 environments will be placed in cascade form one after the other, where our robot will take 50 samples for each environment, each of them will be made of cardboard boxes and conditioned for each situation mentioned.

# 1.1.4 Configuration Sensors
  
  Our robot has 3 analog sensors:
  
  - Sensor for air quality measurement MQ135.
  - Sensor Humidity DHT11.
  - Sensor Temperature LM35(DHT11).